import { ArrowDown, ArrowUpRight, Check, HouseLine, MapPin, Phone, Rows, Wrench } from '@phosphor-icons/react'

const mapsUrl = 'https://maps.app.goo.gl/vh1RwMz9kn56a45p7'

const reviews = [
  { name: 'Laura Ruiz', ago: '1 month ago', text: 'Edder came out and gave me a free estimate, explained all of my options, and made the entire process feel seamless. This was my first time replacing a roof, and he walked me through every step and answered all of my questions.' },
  { name: 'Ryan Prudhel', ago: '1 year ago', text: 'J Roofing, Edder and his team did an amazing job on my roof, seamless gutters and downspouts. They were on time, had great communication and cleaned up daily.' },
  { name: 'Robert Allen', ago: '11 months ago', text: 'I had my large shop and main house reroofed. They replaced all dry rot on the shop. The house and shop look amazing. Edder Ruiz was excellent to work with.' },
  { name: 'eileen laughlin-michael', ago: '2 years ago', text: 'J Roofing was nothing but professional. They worked with us when we needed extra time for repairs, and when the day came they worked hard and took care to leave the area clean.' },
  { name: 'tom tovar', ago: '2 years ago', text: 'From the beginning to the end our experience was extremely satisfying. The professionalism from Edder, Elliot and team was exemplary. We’re so pleased with how our roof came out.' },
  { name: 'Gustavo Tamariz', ago: '4 years ago', text: 'Edder was friendly and punctual. His guys came out and finished the job with a high level of professionalism. The crew cleaned up after every day just as Edder said they would.' },
  { name: 'A. AGARI', ago: '5 years ago', text: 'I first dealt with J Roofing over 12 years ago on my mother’s house. I was so impressed with the quality of work, promptness, competitive price and professionalism that I called them again.' },
  { name: 'Daniel Martinez', ago: '3 years ago', text: 'Edder with J Roofing gave an estimate that was very reasonable, started the roof as planned, and finished it earlier than anticipated—even after repairing unforeseen dry rot.' },
  { name: 'Ronald Warren', ago: '1 year ago', text: 'I was researching several roofing companies in the Stockton area and found a real honest and professional company. They gave me a fair and reasonable price with no hidden cost.' },
  { name: 'Per', ago: '2 years ago', text: 'J Roofing did a phenomenal job on my roof and gutters. Edder was extremely knowledgeable and great at answering all my questions. Elliott and his team completed the job on time.' },
]

const services = [
  { icon: HouseLine, title: 'Roof replacement', text: 'A clear path through options, tear-off, dry-rot findings and a finished roof.' },
  { icon: Wrench, title: 'Roof repair', text: 'Focused help for leaks, damaged areas and repairable roof concerns.' },
  { icon: Rows, title: 'Gutters & downspouts', text: 'Seamless gutter and downspout work mentioned directly by J Roofing customers.' },
]

function Brand() { return <a className="brand" href="#top" aria-label="J Roofing home"><span>J</span><strong>ROOFING</strong></a> }

function App() {
  return <>
    <style>{`.mobile-rating{display:none}.sample-repair,.sample-gutter{padding:0}.sample-repair:after,.sample-gutter:after{display:none}.sample-material img{width:100%;height:100%;object-fit:cover;filter:saturate(.72) contrast(1.12)}.sample-material span{position:absolute;inset:auto 14px 14px;z-index:2;padding:7px 10px;border-radius:6px;color:var(--asphalt);background:rgba(255,254,248,.9);font-size:.72rem;font-weight:700}.craft-gallery{padding:0 max(24px,calc((100vw - 1380px)/2)) clamp(96px,10vw,150px);display:grid;grid-template-columns:1.15fr .85fr;gap:18px;background:var(--mineral)}.craft-image{position:relative;min-height:420px;margin:0;overflow:hidden;border-radius:14px;background:var(--asphalt);box-shadow:0 18px 36px rgba(22,35,33,.16)}.craft-image img{width:100%;height:100%;object-fit:cover}.craft-image figcaption{position:absolute;inset:auto 18px 18px;max-width:360px;padding:12px 14px;color:var(--asphalt);background:rgba(255,254,248,.92);border-radius:8px;font-size:.78rem;font-weight:700}.craft-image:last-child{margin-top:72px}@media(max-width:720px){.mobile-rating{position:absolute;top:-4px;right:0;display:flex;flex-direction:column;align-items:flex-end;color:var(--white);text-decoration:none}.mobile-rating strong{font:600 1.55rem/1 'IBM Plex Sans Condensed'}.mobile-rating span{color:var(--orange);font-size:.55rem;letter-spacing:.07em}.hero{padding-bottom:36px;gap:26px}.hero h1{font-size:clamp(3.5rem,15.5vw,4.2rem)}.hero-lead{margin-bottom:22px;font-size:1rem;line-height:1.45}.sample-deck{height:290px}.sample-rating{top:0;right:1%;width:78%;min-height:78px;padding-inline:16px}.sample-photo{top:58px;height:124px}.sample-repair{top:116px;height:88px;min-height:88px}.sample-gutter{top:178px;height:88px;min-height:88px}.rating-number{font-size:3.4rem}.stars{font-size:.95rem}.sample-material span,.sample-photo span{bottom:7px;padding:4px 6px;font-size:.58rem}.craft-gallery{padding:0 18px 88px;grid-template-columns:1fr}.craft-image{min-height:300px}.craft-image:last-child{margin-top:0}}`}</style>
    <header className="site-header"><div className="nav-shell"><Brand /><nav aria-label="Primary navigation"><a href="#services">Roof systems</a><a href="#reviews">Google reviews</a><a href="#contact">Contact</a></nav><a className="header-call" href="tel:+12094837588"><Phone weight="bold" /> <span>(209) 483-7588</span></a></div></header>
    <main id="top">
      <section className="hero">
        <div className="hero-copy"><p className="location"><MapPin weight="fill" /> Stockton, California</p><a className="mobile-rating" href={mapsUrl} target="_blank" rel="noreferrer" aria-label="4.9 stars from 74 Google reviews"><strong>4.9</strong><span>★★★★★</span></a><h1>Your roof.<br />Done right.</h1><p className="hero-lead">Roof replacement, repair, gutters and downspouts—backed by the words of Stockton homeowners.</p><div className="hero-actions"><a className="button button-primary" href="tel:+12094837588"><Phone weight="bold" /> Call for an estimate</a><a className="button button-quiet" href="#reviews">Read Google reviews <ArrowDown weight="bold" /></a></div></div>
        <div className="sample-deck" aria-label="J Roofing Google rating and roofing craft"><div className="sample sample-photo"><img src="/roofing/j-roofing/assets/j-roofing-crew.webp" alt="Concept image of a roofing crew installing charcoal shingles" /><span>Original crew concept</span></div><div className="sample sample-material sample-repair"><img src="/roofing/j-roofing/assets/j-roofing-shingle-detail.webp" alt="Concept detail of hands aligning architectural shingles" /><span>Shingle alignment</span></div><div className="sample sample-material sample-gutter"><img src="/roofing/j-roofing/assets/j-roofing-gutters.webp" alt="Concept detail of a dark bronze gutter and downspout" /><span>Seamless roofline</span></div><a className="sample sample-rating" href={mapsUrl} target="_blank" rel="noreferrer" aria-label="View J Roofing on Google Maps"><span className="rating-number">4.9</span><span><span className="stars" aria-label="4.9 out of 5 stars">★★★★★</span><small>74 GOOGLE REVIEWS</small></span><ArrowUpRight weight="bold" /></a></div>
      </section>
      <section className="proof-strip" aria-label="Business details"><div><Check weight="bold" /><span><small>GOOGLE RATING</small><strong>4.9 from 74 reviews</strong></span></div><div><MapPin weight="bold" /><span><small>ADDRESS</small><strong>1728 E Market St, Stockton</strong></span></div><div><Phone weight="bold" /><span><small>PHONE</small><strong>(209) 483-7588</strong></span></div></section>
      <section className="services" id="services"><div className="services-intro"><h2>One crew.<br />The whole roofline.</h2><p>J Roofing’s public customer reviews repeatedly mention clear estimates, punctual crews, daily cleanup and careful work—from full reroofs to gutters and dry-rot repairs.</p></div><div className="service-list">{services.map(({ icon: Icon, title, text }) => <article className="service" key={title}><Icon weight="regular" /><div><h3>{title}</h3><p>{text}</p></div><ArrowUpRight weight="bold" /></article>)}</div></section>
      <section className="craft-gallery" aria-label="Roofing craft details"><figure className="craft-image"><img src="/roofing/j-roofing/assets/j-roofing-shingle-detail.webp" alt="Concept detail of hands carefully aligning architectural shingles" /><figcaption>Shingle alignment · Original concept image for this pitch</figcaption></figure><figure className="craft-image"><img src="/roofing/j-roofing/assets/j-roofing-gutters.webp" alt="Concept detail of a seamless gutter and downspout" /><figcaption>Seamless roofline · Original concept image for this pitch</figcaption></figure></section>
      <section className="reviews" id="reviews"><div className="review-heading"><div><h2>Stockton says it best.</h2><p>Ten excerpts from J Roofing’s public Google reviews. Lightly trimmed for length; wording preserved.</p></div><a className="google-link" href={mapsUrl} target="_blank" rel="noreferrer">See all 74 on Google <ArrowUpRight weight="bold" /></a></div><div className="review-grid">{reviews.map((review, index) => <article className={`review-card review-${index + 1}`} key={review.name}><div className="review-top"><span className="avatar" aria-hidden="true">{review.name[0].toUpperCase()}</span><div><strong>{review.name}</strong><small>{review.ago} · Google review</small></div><span className="mini-stars" aria-label="5 stars">★★★★★</span></div><p>“{review.text}”</p></article>)}</div></section>
      <section className="contact" id="contact"><div className="contact-copy"><h2>Start with the roof.</h2><p>Tell J Roofing what you’re seeing and ask for an estimate. One direct call is the shortest path.</p></div><div className="contact-actions"><a className="contact-call" href="tel:+12094837588"><small>CALL J ROOFING</small><strong>(209) 483-7588</strong><Phone weight="bold" /></a><a className="contact-map" href={mapsUrl} target="_blank" rel="noreferrer"><span>Open the verified Google listing</span><ArrowUpRight weight="bold" /></a></div></section>
    </main>
    <footer><Brand /><p>1728 E Market St<br />Stockton, CA 95205</p><a href="tel:+12094837588">(209) 483-7588</a><small>Website concept built from public listing information. Business details, services and final content should be confirmed by J Roofing before commercial use.</small></footer>
    <div className="mobile-call"><a href="tel:+12094837588"><Phone weight="bold" /> Call J Roofing</a><a href={mapsUrl} target="_blank" rel="noreferrer">Google <ArrowUpRight weight="bold" /></a></div>
  </>
}

export default App
